src/components/Scope.js, tests/components/Scope.spec.js
This fixes the issue with the nested scopes issue #32.
=> Fixes issue #32 with nested scopes

src/components/form-fields/RadioGroup.js, src/index.js
https://github.com/joepuzzo/informed/issues/47
=> export BasicRadioGroup

src/components/form-fields/Select.js
Somehow I wasn't able to use the ref for the Select field. I think this was the problem.
By the way I'm well aware I still have to finish #89 ... I just really need to find the time to do it.
=> Corrected the Select forwardedRef.

index.d.ts
Brought Typescript typings up to date with the new API's :)
=> Updated typings

index.d.ts
=> Updating ref to be of type any on FieldContext

README.md
Small fix of typos in code example
=> fixed code example in README.md

src/hooks/useForm.js, tests/components/Form.spec.js
=> Added effects to deregister and reregister form events

index.d.ts
- Allow usage when `tsconfig.json` has `enableSyntheticDefaultImports` off
- add validate method to `FormApi` type
=> Typescript updates

src/hooks/useArrayField.js, src/hooks/useField.js, tests/components/Form.spec.js
- Added initial values to field hook useEffect
- Added check in use array field validation
=> Reregister field api on initialvalues change

src/HOC/asField.js, src/utils.js, stories/CustomInputs/Intro/README.md, stories/CustomInputs/Intro/index.js, stories/index.js, tests/utils.spec.js
Couple random formatting fixes due to your prettier config and VSCode auto-formatting.
=> Fixing display name for asField HOC

stories/Intro/WhatElse/CustomInputs.md
This PR fixes a typo in the docs.
=> Fix a typo in the finishing "Note"

index.d.ts
=> Added allowEmptyString type definition - closes #317

src/ObjectMap.js, tests/ObjectMap.spec.js
=> fix(ObjectMap): fix function reference

index.d.ts
1. Adds export for useMultistepState
2. Updates Multistep typing to remove prop requirement and allow multiple children.
=> Multistep typing improvements.

vitedocs/Pages/GettingStarted/Intro/Intro.jsx
=> Fix typo on Intro page

index.d.ts
delete duplicated type define on line 222
=> Delete duplicated type define.

src/hooks/useForm.js
=> fix typo in useForm.js

vitedocs/Pages/Examples/Tables/ExcelSheet/Example.jsx
This PR implements a refactor of the `Example` table component to improve both readability and performance.
- Extracted constants/setup outside the component to optimize performance
- Implemented `useCallback` for handlers to prevent redundant re-renders
Testing:
=> Refactor `Example` Table Component

index.d.ts, src/components/ArrayField.js
add ArrayField.Items displayName.
=> add more function types define.

index.d.ts, src/FormController.js, vitedocs/Pages/ApiReference/FormApi/MoreExamples.jsx
Added these 2 new functionality to formApi interface:
- clearAllErrors() 
- will iterate through all fields and clear the validation error of each field (if any) by calling clearError(field) on each iteration.
- clearAllValues() 
- will iterate through all fields and clear the value of each field by calling clearValue(field) on each iteration
- Added examples on 'More Examples' page.
Demo:
https://github.com/user-attachments/assets/6161deb5-44c3-4da0-b9c6-156177e35769
=> Add clearAllErrors() and clearAllValues() functions to formApi
